export const enum Paths {
  Login = 'Login',
  Splash = 'Splash',
  Checkin = 'Checkin',
  ChooseShop = 'ChooseShop',
  Settings = 'Settings',
  EditProfileUser = 'EditProfileUser',
  System = 'System',
  Report = 'Report',
  BottomNavigator = 'BottomNavigator',
  BookingManage = 'BookingManage',
  DetailBookingItem = 'DetailBookingItem',
  AddNewBooking = 'AddNewBooking',
  EditBooking = 'EditBooking',
  DashBoard = 'DashBoard',
}
